// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE-2doBUaojy3InqDCuWOsRt5CM1WD6JA',
    appId: '1:452156554877:web:98ce1e0adbafec1c9b3b14',
    messagingSenderId: '452156554877',
    projectId: 'racing-app-72954',
    authDomain: 'racing-app-72954.firebaseapp.com',
    databaseURL: 'https://racing-app-72954-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racing-app-72954.firebasestorage.app',
    measurementId: 'G-3BT9YE5NEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUeHL5xi5z4lVUem9eZ1EDAbmS6oJID0k',
    appId: '1:452156554877:android:e618446b120a9c409b3b14',
    messagingSenderId: '452156554877',
    projectId: 'racing-app-72954',
    databaseURL: 'https://racing-app-72954-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racing-app-72954.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBogIsQmtpIdUQlX2zWUC4pe1n-FMNT8o4',
    appId: '1:452156554877:ios:00db7e36d20d2cd19b3b14',
    messagingSenderId: '452156554877',
    projectId: 'racing-app-72954',
    databaseURL: 'https://racing-app-72954-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racing-app-72954.firebasestorage.app',
    iosBundleId: 'com.example.racingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBogIsQmtpIdUQlX2zWUC4pe1n-FMNT8o4',
    appId: '1:452156554877:ios:00db7e36d20d2cd19b3b14',
    messagingSenderId: '452156554877',
    projectId: 'racing-app-72954',
    databaseURL: 'https://racing-app-72954-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racing-app-72954.firebasestorage.app',
    iosBundleId: 'com.example.racingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE-2doBUaojy3InqDCuWOsRt5CM1WD6JA',
    appId: '1:452156554877:web:a38d2d6acc2ea3789b3b14',
    messagingSenderId: '452156554877',
    projectId: 'racing-app-72954',
    authDomain: 'racing-app-72954.firebaseapp.com',
    databaseURL: 'https://racing-app-72954-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racing-app-72954.firebasestorage.app',
    measurementId: 'G-PH2RPP65N3',
  );
}
